version: '3.8'
services:
  dev-db:
    image: postgres:16.1-alpine3.18
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - freecodecamp

volumes:
  postgres:
    external: false

networks:
  freecodecamp:
