version: '3.8'
services:
  todo-db:
    image: postgres:16.1-alpine3.18
    container_name: todos-db
    hostname: todos-db-host
    restart: always
    ports:
      - 5432:5432 #5434:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:7.7
    container_name: pgadmin
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: superman@google.com
      PGADMIN_DEFAULT_PASSWORD: superman
    depends_on:
      - todo-db

volumes:
  todo-db:
    external: false
